### ISSUE TITLE
Property values clipped off on the Property View

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#100]
See screenshots for illustration. When editing a property value on the Property View, its value is clipped off from top and bottom:

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/11240abb-bf7c-4c4e-8251-476afe8b223e)
![image](https://github.com/obelisk79/OpenTheme/assets/148809153/94abb0f5-6ccf-4f14-96f0-13e1d6978110)

Some values seem to have less or non-perceivable clipping, though:

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/8a6cd422-ea2a-4281-9226-2f814cac0b35)

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38088 (Git) Snap 1071
Build type: Release
Branch: main
Hash: 5568b40a07fac70e70df7f7fe5d60a650418c00c
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

**Comment by obelisk79** [comment]
I believe this issue will be addressed with the next big update I expect to push tonight.
