### ISSUE TITLE
Three View names not resizeable properly. 

### ISSUE THREAD

**Issue by czinehuba** [obelisk79/OpenTheme#101]
The tree view names don't change size properly. I have the resizeable column option enabled, but it only grows to the size that was set before I changed the theme. 
It works with the included light theme.

![image](https://github.com/obelisk79/OpenTheme/assets/48809015/872c8936-e6d9-4820-b9ba-82e6623a2411)

OS: Ubuntu Core 22 (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38088 (Git) Snap 1071
Build type: Release
Branch: main
Hash: 5568b40a07fac70e70df7f7fe5d60a650418c00c
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * fcgear 1.0.0
  * Curves 0.6.40
  * fc_nodes 0.1.36
  * sheetmetal 0.4.21
  * fasteners 0.5.24
  * lattice2 1.0.0
  * freecad_metal_workbench 0.0.1
  * CfdOF.backup1713725901.4016135 1.21.7 (Disabled)
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * 3DfindIT 1.2.0

**Comment by obelisk79** [comment]
I will look into this soon. I do not experience the same problem on my computer so it may be difficult to address.

**Comment by obelisk79** [comment]
I am still unable to recreate this problem. Is the issue still present for you with the latest updates to the theme?

**Comment by obelisk79** [comment]
I am closing this for now. I believe the latest updates have eliminated this issue and I have never been able to recreate this.

**Comment by czinehuba** [comment]
Apologies. I haven't had the chance to respond. Indeed, it's fixed in the latest version. Thank you.
