### ISSUE TITLE
Arrows to scroll through document tabs are transparent

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#102]
When more documents that fit the tab area above the status bar are open, the arrows to scroll through them are transparent

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/2eaeed4b-f413-4278-8c35-8deb3e45d912)

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38120 (Git) Snap 1073
Build type: Release
Branch: main
Hash: 9eeca1f6ad50cea9fa2d30d1a4fbb8b6e8fb4bbd
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

**Comment by obelisk79** [comment]
Related to #10
As with that issue, I am unable to reproduce the effect you see. The buttons have solid fill color and are functional for me.

**Comment by obelisk79** [comment]
I have identified the problem and it appears to be good now.
