### ISSUE TITLE
Tree view text switches between white/black

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#103]
The tree view text switches between black and white. White is not legible with OpenLight.
If I enable and disable visibility for a white text item, it becomes black and is legible again.
@obelisk79 I cannot describe how to reproduce it, when it happens I need to manually toggle all objects individually to make them legible again.
Also, all items in the tree view have a bold font, except PartDesign bodies which are not the active one.

<img width="283" alt="Bildschirmfoto 2024-07-21 um 13 20 47" src="https://github.com/user-attachments/assets/b72fcc99-0d6d-4cc3-a7ef-3aaf6bd08187">

```
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38261 (Git)
Build type: Release
Branch: main
Hash: 51789ae8a1a0b1ed20317eaedcd190baac734e3d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.7.3
  * CfdOF 1.27.4
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.22
  * Curves 0.6.41
```

**Comment by obelisk79** [comment]
Dues the white text persist after restarting FreeCAD? I noticed this recently to. But it's a new issue that didn't appear with any changes to the theme

**Comment by maxwxyz** [comment]
White text is gone after restart. But all tree items are still bold, also not active bodies and features. When I activate a body and then deactivate it, it is not bold anymore, but all other features are bold which looks weird. IMO only the active body and part container should be bold to indicate which are the active ones.

In the following screenshot, no body is active. The non-bold one was activated and then deactivated. The first body was not touched after opening the file.
![Bildschirmfoto 2024-07-21 um 20 06 44](https://github.com/user-attachments/assets/ce41fe33-3cca-4c8f-bf5c-44720c9d86c2)

**Comment by obelisk79** [comment]
The bold text behavior is just not consistent in the application. I'll have to unset it completely in the theme.

**Comment by obelisk79** [comment]
I have removed the font-weight parameter from the stylesheets. This should help. The theme currently applies settings for bold and underline to be set when a body is active. In my testing this behavior is now very consistent. I'm going to close this issue for now, the change will be in the next big update in a few hours.
