### ISSUE TITLE
Sketch WB > Validate Sketch white borders on groups

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#104]
Hi @obelisk79 this needs a bit of love. 
![image](https://github.com/user-attachments/assets/f05ea693-d76c-46b3-87a8-365355c407ea)

**Comment by leoheck** [comment]
The white edge is not good.
Also, this needs extra space between the group title and its content.
It could also have extra space between groups.

**Comment by obelisk79** [comment]
This seems to be a dialog/panel specific issue. I'll try ad figure out the problem this week to get a fix pushed.

**Comment by obelisk79** [comment]
Seems to be resolved now. I'm going to close for now. I'll update the theme files in a couple of hours.
![image](https://github.com/user-attachments/assets/0395d216-7771-447a-8cea-aef0ab338bb6)

**Comment by leoheck** [comment]
Nice, thanks. The thick gray line right after the group title doesn't look good too.
