### ISSUE TITLE
Improve selected fields (checkboxes, inputfields)

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#107]
Cannot find selected checkboxes 

Here the selection is on the input field.
And this is not quite visible either. However, I know the selection is there because the cursor is blinking.
However, this can be improved too.
![image](https://github.com/user-attachments/assets/d92250e8-eb3f-4c35-8bd1-679b0f43bb79)

If I hit Tab, the selection goes to the `Symmetric to plane`. But nothing is telling me that.
![image](https://github.com/user-attachments/assets/f93a2f3f-791e-4f5a-a79b-f936bab2026d)

How do I know the item is selected?
If I hit the spacebar, it should check the box.
![image](https://github.com/user-attachments/assets/2c5ea255-4e02-49c8-824d-15e8eb5ba829)

When the mouse hovers the input field on `Length`, the situation worsens since the input field is now highlighted but focuses on the `Symmetric to plane`.

**Comment by obelisk79** [comment]
so, I've experimented with some edits for this issue, and they are working acceptably, however, I don't know if this would be considered an improvement since keyboard navigation within the panel is disastrous at its core. I'm going to sit on this a couple more days to think on whether or not I want to add this change.

**Comment by leoheck** [comment]
Please, continue. I have an issue report saying the navigation is a bit chaotic. They asked examples and I could not provide at that time since I couldn't remember problematic places. But this issue here refreshed my memory since it has screenshots.

**Comment by leoheck** [comment]
The Sketch Edition has them same issues too. It is quite hard to see selected edges, some colors sometimes do not show right. I am going to open another issue with this here, later. And maybe on Freecad too.
