### ISSUE TITLE
Dark theme letters XYZ of origin are black instead of a lighter color

### ISSUE THREAD

**Issue by michaelhq** [obelisk79/OpenTheme#109]
Windows 11 with FreeCAD 0.21.2

I like the dark theme very much! But for me, the letters XYZ of origin are black instead of a lighter color.

I did not find anything in the settings of FreeCAD. Perhaps it cannot be changed. Or do I miss an existing setting? Could it be changed?

![grafik](https://github.com/user-attachments/assets/ef3c1da9-40be-4266-980f-278a02fc3ad6)

**Comment by obelisk79** [comment]
If I remember correctly, these letters could not be changed. This is partially why I have the theme disable that's axis representation by default since the navicube also has axis lines. I will look into this further, thank you for the report.

**Comment by obelisk79** [comment]
I have resolved this. Update your theme installation and the text should be properly set for OpenDark/OpenLight.
