### ISSUE TITLE
Tooltips are hiding menu options

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#114]
It is hard to navigate through menus, since the tooltips are quick to appear, cover the menu options and take time to disappear once the mouse changes to another option

For instance:
1. Select the `Part Design` Workbench,
2. then click the `Part Design` Menu on top.
3. Hover over `Create a local coordinate system` and see the tooltip, 
4. move the mouse to the next item

**Comment by obelisk79** [comment]
I've been digging around all over the place for any hidden clues that I could do something about this through these themes. This behavior also seems present in all themes so I'm going to close this as I am fairly confident I cannot control this in any way.
