### ISSUE TITLE
Enable/Disabled distinctions in DarkTheme

### ISSUE THREAD

**Issue by JohnAD** [obelisk79/OpenTheme#115]
For the input and label elements commonly used with forms, visually distinguishing enabled vs disabled state would be very useful.

To give an example, I added all those items to a dialog:

![opendark](https://github.com/user-attachments/assets/bffb99a3-563d-486b-911a-d044fd4953fc)

The enabled items are on the left. The same items disabled are on the right.

For comparison, the same dialog with no theme added:

![no-theme](https://github.com/user-attachments/assets/a3ec315a-8221-4e69-a357-544c4f337ad8)

**Comment by JohnAD** [comment]
Here is the code I used to test this. It's a tiny standalone Python app with the theme cut & pasted and the dialog in a `.ui` file.

I also see it in the FreeCAD proper, but FreeCAD probably is doing other stuff with the theming, so I doubt it _exactly_ matches. So, this example is really only for showing the `disabled` formatting.

[themeText.zip](https://github.com/user-attachments/files/16645642/themeText.zip)

**Comment by obelisk79** [comment]
PlainTextEdit and TextLabel don't appear to be used in FreeCAD anywhere and aren't even defined in my stylesheet. I can add them if you need to use them, but there should be comparable alternative widgets to use instead.

**Comment by JohnAD** [comment]
Oh, for the file 'main.py' you will want to uncomment lines 10 to 12 to turn on the theme.

**Comment by JohnAD** [comment]
TextLabel == QLabel . I should have used different text on that one.

**Comment by obelisk79** [comment]
fixed https://github.com/obelisk79/OpenTheme/pull/116

**Comment by JohnAD** [comment]
looks great! thanks.

![image](https://github.com/user-attachments/assets/eb3d934c-86cf-45e3-b714-d91ed6eeacd4)
