### ISSUE TITLE
Improvement: Non-Construction line and External geometry quite the same color.

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#123]
Can we have the colors between Non-Construction line and External geometry improved on Dark theme? They are quite the same if they are not the same color.  It would be nice to differentiate them better/easier.
![image](https://github.com/user-attachments/assets/040afd93-7c3f-413f-8adc-dd3b9f05cf87)

**Comment by obelisk79** [comment]
I tagged you on Discord with this comment, but I'll post it here as well:

External Geometry reference lines are purple and construction lines are blue... I'm not sure I understand the issue. Do you have color perception deficiency by chance?  I did my best to make the color selections the most broadly accessible for color impairment but it's not possible to make it perfect for all 6 types of color deficiency.

**Comment by leoheck** [comment]
> I tagged you on Discord with this comment, but I'll post it here as well:

Thanks, it is a bit hard to find things there.

> Do you have color perception deficiency by chance?

Maybe.. not that I am aware of. But these too hard to distinguish. Well, at least these have different line styles to help a bit further.

Do you think there is no space for improvement on this issue?

**Comment by obelisk79** [comment]
I've checked with others regarding these colors and the response has been that they are well defined. Because so many colors are used in sketcher there aren't many options left. 

In your case, the best option may be to customize those two line colors in your preferences. . I'm also open to suggestions.
