### ISSUE TITLE
List based property editor colors are bad (always primaryText over yellow background)

### ISSUE THREAD

**Issue by mnesarco** [obelisk79/OpenTheme#126]
Yellow background is hard coded in FreeCAD, so they have to fix it there or the theme should use fixed text color for this special case to have good contrast with the unchangeable yellow background.

![image](https://github.com/user-attachments/assets/069e673d-f002-4cb8-8bbd-c8ca37abd12c)

FreeCAD bug report:
https://github.com/FreeCAD/FreeCAD/issues/16454

**Comment by obelisk79** [comment]
Hi Frank, thank's for the report. I still may be able to override the color via stylesheet, but I'll have to play around with it next time I'm sitting down to work on fixes. I haven't had much free time this week.

**Comment by mnesarco** [comment]
I can try to fix it in the stylesheet if you give me an idea of how to override the c++ selection attribute. afaik it is not possible using just qss in this case, but i have not worked with qss in a long time.

**Comment by obelisk79** [comment]
I use a Qt inspection too called GammaRay on the application while running to get widget type and name, then you can target those specific named widgets for an override.

**Comment by mnesarco** [comment]
> I use a Qt inspection tool called GammaRay on the application while running to get widget type and name, then you can target those specific named widgets for an override.

No the problem is not widget selection. The problem is that color is actively set by c++ code on selection event. Even if you declare the right rule in the qss file, the color is set by c++ code when the selection changes.

**Comment by mnesarco** [comment]
A video says more than thousand words:

https://github.com/user-attachments/assets/04c119d9-9e5e-4a45-978d-4255da3786e1


1. Create a VarSet
2. Add a property of type App::PropertyStringList
3. Click the three dots button in the property editor

**Comment by obelisk79** [comment]
I agree this either cannot be styled directly via stylesheet or it is incredibly difficult to target. I also noticed that on my end it isn't inheriting button styling properly either. Quite frustrating.

**Comment by obelisk79** [comment]
Awesome news!
