### ISSUE TITLE
Sketch: Under-constrained sketch colors are not helping since it looks like constrained.

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#131]
Somethims under constrained are also green...
I am just not sure if this is an issue for the theme maker or the Freecad itself.

I am sharing the file here first, [diff_tool_issue.FCStd.zip](https://github.com/user-attachments/files/17174630/diff_tool_issue.FCStd.zip)

![image](https://github.com/user-attachments/assets/283d794b-9952-4dde-a66c-acf5251b0e0a)

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38843 (Git) AppImage
Build type: Release
Branch: main
Hash: d519f24df9931e4a98d19ee39cdcd6124ae6a7bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.9

```

**Comment by obelisk79** [comment]
I don't understand what the problem you are reporting is?

**Comment by obelisk79** [comment]
Partially constrained elements are going to show green. 

Fully constrained is also green, with only a slight color variation. This is intentional.

**Comment by leoheck** [comment]
hm, I find this a bit unclear because it uses the same green but darker.

And the confusion came since the Sketch started constrained (bright green) and not "not constrained (white)" then I changed something small, and it was still green (not the bright one tho) but the Sketcher was telling me it was not fully constrained.

Well, thanks for the explanation mate.
