### ISSUE TITLE
Dark: Checkboxes use black ticks on dark background

### ISSUE THREAD

**Issue by krissrex** [obelisk79/OpenTheme#16]
![image](https://github.com/obelisk79/OpenTheme/assets/7364831/2f20b019-9b9e-421b-898c-2c493b31ddf7)

The ticks should probably be white, or the checkbox background white.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Norwegian Bokmal/Norway (nb_NO)
Installed mods: 
  * A2plus 0.4.62
  * Help 1.0.3
  * OpenTheme 2024.4.20
  * Render 2023.8.18
```

**Comment by tooxo** [comment]
I just had the same issue so I tried looking into it. I found out that the scss defines a checkbox indicator color that seems to be bright enough (#dee2e6), but I am not familiar enough with the project to diagnose why it isn't displayed in the UI.

**Comment by hasecilu** [comment]
I think this is already solved, could you check it?

**Comment by krissrex** [comment]
> I think this is already solved, could you check it?

I will try. Should I use stable FreeCAD `0.21.2` or lastest/nightly/dev FreeCAD?

**Comment by obelisk79** [comment]
A weekly build if possible.
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by krissrex** [comment]
Yes, it is fixed :)
