### ISSUE TITLE
Dark: Spreadsheet uses black text

### ISSUE THREAD

**Issue by krissrex** [obelisk79/OpenTheme#17]
![image](https://github.com/obelisk79/OpenTheme/assets/7364831/af7a0620-005e-48ac-817c-ea096eeddf1a)

The text should probably be white.

The cell color selector says black/white, but those only apply if I change them. It believes white is the background, so I must change it to e.g. red, then back to white. I'm not sure if this has any implications for this theme.

**Comment by obelisk79** [comment]
This should now be resolved.
