### ISSUE TITLE
right click menu in workbench preferences page has black background

### ISSUE THREAD

**Issue by adrianinsaval** [obelisk79/OpenTheme#19]
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/a208c159-426c-4203-8821-e65b06e0f440)

also happens in opendark, not sure if it's intended there as I see other menus use grey in the rest of the app
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/e2c5e5fd-7af8-461f-950c-0e146626b7da)

**Comment by obelisk79** [comment]
This is unusual behavior, isolating this specific menu is challenging. I'm trying to make a big push this week on theme issues, I'll do my best to figure this one out.
