### ISSUE TITLE
Clipping plane checkboxes not visible

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#24]
OpenLight/OpenDark both affected.
The checkboxes on Windows are rendered the same way if they are checked or not. It is not possible to see the checkmark:
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/5776f96c-d937-459a-b661-afb1fa1278b0)

**Comment by maxwxyz** [comment]
In OpenLight it's even worse, the checkbox is not recognized:
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/f2aa0ad6-bcf7-4762-9a11-2dce1d3a3e07)

@obelisk79 FYI

**Comment by obelisk79** [comment]
@maxwxyz can you confirm if this is still present? I worked on checkboxes in groupbox widgets last month for this issue in the preferences dialog but never followed up on clipping plane.
