### ISSUE TITLE
TabBar tabs have wide empty right margin

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#25]
When configured to show only icons, the TabBar's tabs have a wide, blank-spaced margin on the right. For visual consistency and to save screen space, the right and left margin spacing should probably be the same.

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/0f278ff2-caf1-417b-abe4-b0a552fdebc6)

**Comment by furgo16** [comment]
This seems to be related to https://github.com/FreeCAD/FreeCAD/pull/14592

**Comment by kadet1090** [comment]
Oh, I forgot to put out the PR! I shall do that tomorrow.

**Comment by shaise** [comment]
> Oh, I forgot to put out the PR! I shall do that tomorrow.

Any news on that?

**Comment by kadet1090** [comment]
Done, sorry for having wait so long - a lot of stuff is going on recently and I have problems with joggling everything around
