### ISSUE TITLE
Progress bar indicator is missing alignment

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#26]
On the Classic theme the progress bar percentage indicator is centered in the middle of the toolbar. On OpenTheme the percentage indicator is left aligned and too close to the left margin, which probably hints at its alignment not having been set.

This can be tested using the Add-on Manager and clicking on Check for updates.

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/98601326-90b4-4940-905e-b4446137f675)

**Comment by hasecilu** [comment]
I think this nos is fixed, could you check?

**Comment by furgo16** [comment]
This is now fixed, thanks!

Progress bars are not yet functional due to https://github.com/obelisk79/OpenTheme/issues/82, though.

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38039 (Git) Snap 1067
Build type: Release
Branch: main
Hash: 7a9fd501c3ea0e259f843dc21f488ef6af43c201
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
```
