### ISSUE TITLE
Spreadsheet text color is white on white for OpenLight

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#29]
Text within spreadsheet cells is not visible using the OpenLight theme, as the text color is white (`#f8f8f2`). See cell `A1` in the screenshot for an example:

![Captura de pantalla de 2024-05-02 15-39-34](https://github.com/obelisk79/OpenTheme/assets/148809153/99291b60-4d2b-4f28-93e0-6d2296d8af45)

It should be set to `#000000` or a darker color than the cell background.

I noticed these lines in the code, but I'm not sure if that's the right location for this change. If it is, happy to send a PR:
https://github.com/obelisk79/OpenTheme/blob/b6784d55b3bab9a225c91941e5a8a38f0e0c61e9/OpenLight/OpenLight.cfg#L103-L107

**Comment by furgo16** [comment]
Related issue https://github.com/obelisk79/OpenTheme/issues/17. It would seem that the text color values have been swapped between themes.

**Comment by obelisk79** [comment]
Thanks for the report, and the research. I'm sorry it took so long to resolve. Both themes have their spreadsheets working correctly now.

**Comment by furgo16** [comment]
Great, thank you!
