### ISSUE TITLE
vertical wb selector too wide on icons only mode selector toolbar addon broken when placed vertically

### ISSUE THREAD

**Issue by adrianinsaval** [obelisk79/OpenTheme#33]
This is what I'm seeing:

![image](https://github.com/obelisk79/OpenTheme/assets/36372335/2dab4446-4c8d-48c0-8a79-648b7722eb6b)

I'm trying to replicate what I previously used with selector toolbar addon:
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/7ef922d1-2535-4cce-81cb-ea3b32ad2fad)

which btw ias also not working with opendark when placed vertically
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/50d974c9-25b6-4e3e-bfb6-c9cae9efe1b4)
works fine when placed horizontally:
![image](https://github.com/obelisk79/OpenTheme/assets/36372335/272e0902-9688-4e64-a1ec-6bfd3d8f0019)

**Comment by kadet1090** [comment]
@adrianinsaval can you check? I feel that I fixed it in https://github.com/obelisk79/OpenTheme/pull/58

**Comment by kadet1090** [comment]
I meant mostly the official tabbar

**Comment by obelisk79** [comment]
This issue should now be resolved.
