### ISSUE TITLE
Snap circle indicator is not visible

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#35]
See attached screenshot. When snapping to the grid (e.g. creating a line with the Draft workbench), the circle that indicates the snapping point is white on off-white, making it nearly invisible and difficult to snap.

![image](https://github.com/obelisk79/OpenTheme/assets/148809153/b45a0476-f3d9-4003-a1fc-2a7ef7ebea05)

```
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37108 +1 (Git)
Build type: Unknown
Branch: arch_materials_fix
Hash: 09021f40a95ed6d6cd42f7736da29ecdca9b38a8
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Installed mods: 
  * OpenTheme 2024.5.3
  * BIM 2021.12.0
  * parts_library
```

**Comment by obelisk79** [comment]
Thanks for the report, I've updated OpenLight and this should now be resolved.
