### ISSUE TITLE
TechDraw: Projection Group task dialog - too large icons and text

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#36]
the font in the center is too large and the icons and checkboxes seem very huge
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/cb463058-67a8-4f18-96d4-96e58804b17a)

**Comment by obelisk79** [comment]
This appears to now be corrected in both OpenLight and OpenDark, I'm going to close this out.
