### ISSUE TITLE
TechDraw Preferences: Line Styles

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#39]
The icons only have a white background on the selected one which is ok for me as the drawings will always be on a white background. Not sure if the blue overlay of the hovered/selected one could be drawn behind the preview (currently it is above)

![292121113-74039ae0-fe47-4a3a-b5ac-b13671ca8854](https://github.com/obelisk79/OpenDark/assets/6246609/90c0db5f-34e5-48d0-af69-758209cce4d7)
![image](https://github.com/obelisk79/OpenDark/assets/6246609/21af97eb-affd-4f4a-97e2-0ab548a2c146)

**Comment by obelisk79** [comment]
After further investigation, I have no control over this rendering, and ti appears to not be something present on all platforms since I can't recreate the behavior. I think this may be a code-level or Qt issue.
