### ISSUE TITLE
AnnotationLabel not legible

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#4]
The new measurement tool uses AnnotationLabels `App::AnnotationLabel` which are not legible with OpenTheme (Dark or Light).

The colors can be set in the preferences.
![image](https://github.com/obelisk79/OpenTheme/assets/6246609/61a8eb7f-20b9-4b55-8bcb-30fca95c504c)

https://github.com/FreeCAD/FreeCAD/issues/13116
The text color and background color is always black. The leaderline is always white.
![image](https://github.com/obelisk79/OpenTheme/assets/6246609/0060c681-bb31-4759-a601-02c8879de45f)

Proposal:
- OpenDark: White leader line, dark background with white outline and white text.
- OpenLight: Dark leader line, white background with dark outline and black text.

**Comment by obelisk79** [comment]
This looks very different on my machine.
![image](https://github.com/obelisk79/OpenTheme/assets/17993710/af178977-32d2-4575-bfc0-153bb0a5275d)

**Comment by obelisk79** [comment]
I'm also unable to access the measure settings, perhaps I'm using the wrong tool/toolbar?

**Comment by obelisk79** [comment]
My experimentation with the measurement tools has me frustrated. This doesn't seem to work properly or consistently.
![image](https://github.com/obelisk79/OpenTheme/assets/17993710/aa945aeb-5bb8-473c-ab70-3a3012c1e447)

**Comment by maxwxyz** [comment]
The tool is not merged yet and will replace current tools. It's the GSoC unified measurement tool PR

**Comment by obelisk79** [comment]
Eta on the PR getting merged?

**Comment by maxwxyz** [comment]
I hope this month

**Comment by maxwxyz** [comment]
@obelisk79 the tool was merged today, so this could be set in OpenTheme now

**Comment by maxwxyz** [comment]
I propose the color #3ef008 for line and background color. Text color should be black.
