### ISSUE TITLE
TechDraw: Dimension Task View

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#40]
Tolerances in Dimension feature of TechDraw WB are not readable:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/28cb1304-b402-4ab5-91df-8f2bc827bfda)

**Comment by kadet1090** [comment]
Still an issue?

**Comment by maxwxyz** [comment]
Yes, still present. In almost all input boxes, also in property view 
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/fb904639-9a05-4eea-ba8b-ce8369ac7ead)

**Comment by kadet1090** [comment]
This must be due to scaling as for me the issue is no longer present

**Comment by maxwxyz** [comment]
It's no problem with the classic theme so I guess it is related to OpenTheme?

**Comment by obelisk79** [comment]
This one was a bit tricky to isolate on my end. The QLineEdit embedded in a QAbstractSpinBox was very sensitive. I think I've got it sorted. At least on my side. This will push with the next update.

![image](https://github.com/user-attachments/assets/5729cb6e-50c4-483c-9500-435874604963)
