### ISSUE TITLE
Sketcher: Unable to read selected or hovered constraints

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#41]
The current colors in the sketcher WB are hard to read against the background for:
1. selected constraints
2. hovered constraints

![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/0e7ed974-c36e-4143-80fe-100703420066)

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35449 (Git)
Build type: Release
Branch: main
Hash: f3fa2ba9c9b1999e5c32d3ae544481b6e17553bb
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.24.9
  * CurvedShapes 1.0.5
  * Curves 0.6.19
  * Defeaturing 1.2.1
  * fasteners 0.4.75
  * FEMbyGEN 2.0.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.3.13
  * woodworking 0.21.1.33694
```

**Comment by obelisk79** [comment]
The intent is to shift towards a singular color for hover and selected state. However it is difficult in Dark themes, because there isn't a separation of selection colors between 3d view (aka your object) and sketch view. I'll do some experimentation.

**Comment by obelisk79** [comment]
Updated the color. I think it works fairly well. Closing for now. PM me on discord if you want to discuss the actual color choice from a stylistic perspective rather than contrast.

![image](https://github.com/obelisk79/OpenTheme/assets/17993710/059d26c7-d752-4749-9716-c8217c584ea0)
