### ISSUE TITLE
Spreadsheet: unable to change text color

### ISSUE THREAD

**Issue by Stu142** [obelisk79/OpenTheme#42]
When using the spreadsheet, I like to color code cells, but the white text is not readable in all colors. I would like to be able to change the text color in the spreadsheet, but this currently does not work with Open Dark. 

This happens on every preference pack other than the classic so may not be possible, but it would be a really nice addition and increase the usability a lot for me. 

OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * Assembly4 0.50.4
  * dodo 1.0.0
  * fasteners 0.4.73
  * freecad.gears 1.1.0
  * IconThemes
  * OpenDark 2023.12.17
  * PythonWorkbenchTemplate-master

![image](https://github.com/obelisk79/OpenDark/assets/74122014/b4f95cbe-ab13-43db-acb4-ae5a40b2d4ee)

When I switch to the classic theme without changing anything else the text becomes the color I set it to be but that didn't show  with open dark enabled. 

![image](https://github.com/obelisk79/OpenDark/assets/74122014/18161c0c-4b1e-4090-a840-a3efbb9fb7fc)

**Comment by obelisk79** [comment]
This should now be corrected. I've been able to modify text color locally, report if it still isn't working as intended.
