### ISSUE TITLE
Text in loading bar not centered. Inactive loading bar renders white

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#45]
Text in loading bar (bottom right status bar) not centered (visible when loading large files)
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/5efe2844-d311-4ea3-9e0d-d18ac81006d7)

**Comment by kadet1090** [comment]
Centering is probably more of issue in FreeCAD code - not theme
