### ISSUE TITLE
TechDraw: Property view - transparency overlay not readable

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#48]
I think this was already mentioned somewhere but I did not find an issue here.
![image](https://github.com/obelisk79/OpenDark/assets/6246609/b779c5e2-f7d1-4e6b-a0f0-fba43a924377)

**Comment by maxwxyz** [comment]
@obelisk79 with the recent fix in main it seems there is a color missing now:
![grafik](https://github.com/user-attachments/assets/88df5eb7-c212-47c0-89fd-4c9b2e854f34)

**Comment by obelisk79** [comment]
This is fixed. Will be in the next update.
