### ISSUE TITLE
MacOS: Light - Navicube white when not hovered

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#5]
on macOS the navicube is white and not legible when not hovered. when hovered its legible and slightly blue like the normal display on Windows with OpenLight
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/2228efdb-0dc0-4883-9f89-0d61017ac354)

**Comment by maxwxyz** [comment]
same is with the grid: it is white in OpenDark and also white in OpenLight, only on macOS. Cannot reproduce on Windows.
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/3546ec16-f2cb-4c63-bbf9-5ac24ffb2478)

@obelisk79 FYI

**Comment by obelisk79** [comment]
This was happening to me also on linux, but it happens for me on all themes. Not just the OpenThemes.

@kadet1090 is this something you are willing to investigate at the code level in FreeCAD?

**Comment by maxwxyz** [comment]
Is this also the same issue on macOS:
Creating e.g. a new additive box in PartDesign is almost invisible:
<img width="628" alt="grafik" src="https://github.com/obelisk79/OpenTheme/assets/6246609/32165a8e-e6a6-4812-8c6b-43f35556927e">

```
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37841 (Git)
Build type: Release
Branch: main
Hash: 5f761c758e2a0164b00a7183b9c0cbe32688e123
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * 3DfindIT 1.2.0
  * freecad.gears 1.2.0
  * OpenTheme 2024.6.22
  * CfdOF 1.25.17
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.19
  * Curves 0.6.39

```

**Comment by maxwxyz** [comment]
also the rotation indicator is not visible against the background, only when geometry is behind it:
<img width="519" alt="grafik" src="https://github.com/obelisk79/OpenTheme/assets/6246609/51394a02-f53a-4d86-83b5-cb605ea30e1c">

seems to be an issue with semi transparent UI on macOS?
@kadet1090 any ideas?

**Comment by obelisk79** [comment]
I do think this is OS specific, in either case I believe it to be a software issue and not a theme issue. I'm going to close this as unplanned.
