### ISSUE TITLE
TechDraw: Pre-Selection Color is Orange

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#50]
In most workbenches and the 3D view the preselection is blue and selected elements are green. In the TechDraw WB the preselection is orange. It should be consistent over multiple WBs
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/e1468cd8-b846-4e80-9264-be8c46da3244)

**Comment by obelisk79** [comment]
I'm shifting both opendark and openlight to a teal selection color. This will be in the next update.
