### ISSUE TITLE
Arch/Draft: Lines/Geo almost invisible

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#51]
In Arch and Draft it is almost impossible to see geometry against the background.
The following example shows two lines. The lines itself are very thin and black on dark background. Hovered and selected are blue/green and visible but still very thin.
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/f8150303-015f-46da-b700-30951224150f)

**Comment by obelisk79** [comment]
Ok, so I've looked into this. The draft line color is directly tied to the line color for 3d objects. I can set it to a lighter color for OpenDark, but I think there will be issues with 3d objects having light colored edges. I think this requires a feature request to fix for the theme.

**Comment by obelisk79** [comment]
Auto-adjusting for colors-aside, I have a solution for this in OpenDark that should cover the essential usability. I'm going to close this and the update will push tonight.
