### ISSUE TITLE
Tree view triangles pixelated

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#52]
In comparison to the Body and Box icon, the triangles for collapsing and expanding appear pixelated on a HiDPI screen on Windows.
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/2d636b39-9f9d-4e08-b00a-ff60328b0a4f)

**Comment by maxwxyz** [comment]
any news on this?

**Comment by obelisk79** [comment]
These inconsistencies are now resolved.
