### ISSUE TITLE
Light: dimension dialog box background color too dark

### ISSUE THREAD

**Issue by jacprog** [obelisk79/OpenTheme#54]
Blue background in input box makes text hard to read
Once the dimension is selected and the box open, the text is the only way to know witch dimension is edited

<img width="1115" alt="dimBox" src="https://github.com/obelisk79/OpenTheme/assets/23371617/9539b70d-d316-4284-9f43-f619eb784102">

**Comment by obelisk79** [comment]
@jacprog I'm sorry, can you confirm that you have the OpenLight theme applied here? Reviewing this, it appears you are using one of the built in light themes and not OpenLight.

**Comment by obelisk79** [comment]
I'm closing this because it is not one of the OpenThemes.
