### ISSUE TITLE
WB Selector UI broken

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#59]
in the latest weekly the ComboBox WB selector is broken in OpenDark and OpenLight.
The horizontal line separating stacked toolbars is not visible underneath the workbench selector, in both OpenLight and OpenDark:
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/7c44330b-f775-4559-8f98-5a910927b897)

Also, the first time I click on the dropdown, I just see the outline and it takes about one second to load the content. This is only happening with the OpenTheme.

@kadet1090 @obelisk79 FYI

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37302 (Git)
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.25.13
  * Curves 0.6.36
  * dodo 1.0.1
  * fasteners 0.5.21
  * freecad.gears 1.2.0
  * OpenTheme 2024.5.3
  * OpticsWorkbench 1.0.17
  * Rocket 3.3.0
  * sheetmetal 0.4.14
```

**Comment by obelisk79** [comment]
Ugh, I know exactly what caused this. I'm not happy about it either, because in TabBar mode I want that line gone, so this wasn't entirely accidental. Regarding the delay, that doesn't make much sense to me. I have a bunch of performance problems in-general on my system.

**Comment by kadet1090** [comment]
The performance aspect is strange. About the line I can expose some additional information to the toolbar so you can target this case specifically

**Comment by obelisk79** [comment]
> About the line I can expose some additional information to the toolbar so you can target this case specifically

I would appreciate something like that.

**Comment by maxwxyz** [comment]
Bug is still present, also on macOS

**Comment by maxwxyz** [comment]
@obelisk79 what's the solution here? IMO it really destroys the UI like this, especially when the combobox is the default UI.

**Comment by obelisk79** [comment]
I admittedly really dislike having the border there while using the tab bar selector. However, last night I added it back in for the sake of consistency. I may have to maintain a custom build of the theme for myself with no border. The change will push with the next theme update so I'm going to go ahead and close this now.
