### ISSUE TITLE
Differentiate radio buttons from checkboxes

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#61]
![image](https://github.com/obelisk79/OpenTheme/assets/148809153/f15cdecc-723d-4f3a-8ea6-3151ad4b41ef)

Notice the **Import** (checkboxes) and **Create** (radio buttons) rows in the screenshot. In most system themes the convention is to have checkboxes as boxes and radio buttons as circles. However, on OpenTheme they are both boxes. This brings some issues:

1. It breaks existing UI conventions. Not an issue per se, unless there is a specific motivation, although it can confuse users
2. It makes it difficult to visually differentiate between the two. One cannot tell which is which before clicking on them.
3. The current implementation clips the bottom of the box for radio buttons

This same screenshot using the Classic theme:
![image](https://github.com/obelisk79/OpenTheme/assets/148809153/4d1c0b4c-9f54-417e-8e49-57cc182a2d4f)

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37330 (Git) Snap 1022
Build type: Release
Branch: main
Hash: a094bf0df7e2b3e5c5b2e3b158a9040a6474892f
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.5.16
  * Curves 0.6.36
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.5.6.01
  * OpenTheme.backup1715920329.3075469 2024.4.20 (Disabled)
```

**Comment by obelisk79** [comment]
This is a regression. Radio buttons were never supposed to be formatted like checkboxes. Should be an easy fix. I'll get on this soon.

**Comment by obelisk79** [comment]
This is now resolved.
