### ISSUE TITLE
Bold text headers clipped in Preferences

### ISSUE THREAD

**Issue by furgo16** [obelisk79/OpenTheme#62]
![Captura de pantalla de 2024-05-17 07-17-09](https://github.com/obelisk79/OpenTheme/assets/148809153/9232d6db-2153-4143-a4f2-aa12b2423db6)

Notice the "Automatic update [...]" and "Import options" headers in the screenshot. They are clipped in height from the top, probably because their style is bold. The issue does not appear with the Classic theme, since it has regular text. This might not be an issue with OpenTheme but with FreeCAD itself, but I thought I'd mention it here for awareness.

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37330 (Git) Snap 1022
Build type: Release
Branch: main
Hash: a094bf0df7e2b3e5c5b2e3b158a9040a6474892f
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.5.16
  * Curves 0.6.36
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.5.6.01
  * OpenTheme.backup1715920329.3075469 2024.4.20 (Disabled)
```

**Comment by obelisk79** [comment]
It's interesting, because the effect isn't visible like that on my computer. Neither was the radio button clipping. My next commit will include a small margin added to hopefully address this. Are you on 1080p resolution?

**Comment by obelisk79** [comment]
Please try inserting the following at the bottom of OpenLight.qss and let me know if that resolves the issue.

```
QGroupBox {
  margin-top: 1.5ex; }
```

If that doesn't work try
```
QGroupBox {
  padding-top: 1.5ex; }
```

**Comment by furgo16** [comment]
One of my monitors is 1080p, but the other one has slightly less resolution. I can see the issue on both. It's also visible here using another platform (Windows) https://github.com/obelisk79/OpenTheme/issues/46#issuecomment-2117083888

I'll try the fixes above and report back.

**Comment by furgo16** [comment]
The first snippet seems to fix the issue:
```css
QGroupBox {
  margin-top: 1.5ex; }
```

Before:
![image](https://github.com/obelisk79/OpenTheme/assets/148809153/fa20989f-af40-4447-ac83-f76991072414)

After:
![Captura de pantalla de 2024-05-17 13-21-07](https://github.com/obelisk79/OpenTheme/assets/148809153/b9b2946e-58ea-44ce-be1d-604de05b8eb4)

**Comment by obelisk79** [comment]
Ok, I'll commit the change shortly.

**Comment by obelisk79** [comment]
done
