### ISSUE TITLE
Preferences have duplicate indicators for indentation

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#69]
Not sure what the right wording for those is. In the preferences you have two vertical lines for expandable sub menus / indicators for indentation:
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/a00cb10c-8594-4ec6-9e11-9240707d2bb1)

In the tree view it looks correctly:
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/abe4f631-c66a-4ec2-bfcd-ff1ec3c9d4af)

Happens in both, Dark and Light.

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git)
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.25.16
  * Curves 0.6.37
  * dodo 1.0.1
  * fasteners 0.5.21
  * freecad.gears 1.2.0
  * OpenTheme 2024.5.16
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.14

```

**Comment by obelisk79** [comment]
This isn't actually a bug, the tree is rendering the way it is coded to. Those are treebranch images. I don't think they are necessary here. I will try and null the images for just this window.
