### ISSUE TITLE
Classic theme cannot be fully restored

### ISSUE THREAD

**Issue by FEA-eng** [obelisk79/OpenTheme#84]
Those themes are really great but the biggest problem for me is that it's not possible to fully bring back the Classic theme. Elements of OpenThemes stay there all the time.

Classic (before applying OpenLight):

![before](https://github.com/obelisk79/OpenTheme/assets/59876896/58adb20c-9fd1-4a42-91aa-8028cfa08631)

OpenLight:

![after 1](https://github.com/obelisk79/OpenTheme/assets/59876896/ceb7c09b-5053-416c-aab3-ab9e22cddc75)

Classic (after switching back from OpenTheme and restarting FreeCAD):

![after 2](https://github.com/obelisk79/OpenTheme/assets/59876896/ad26ecd3-c112-4a42-bd33-e67c1ffb4267)

```
OS: Windows 10 build 19041
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * OpenTheme 2024.6.22
```

**Comment by obelisk79** [comment]
This is probably some setting that classic theme doesn't properly cover. Rather than the other way around.

**Comment by FEA-eng** [comment]
> This is probably some setting that classic theme doesn't properly cover. Rather than the other way around.

So I should post it in the main repo? I’ve tried with the new built-in light and daro themes and it doesn’t happen.

**Comment by obelisk79** [comment]
Since open themes sets the qt style to 'fusion' in the users config, I'm willing to bet that is what is persisting. 

Using the parameter editor, remove the key QtStyle found at BaseApp > Preferences > General

Then see if it looks like you expected.

**Comment by FEA-eng** [comment]
@obelisk79 That indeed helped. Should I create an issue regarding this key not being reset in main?

**Comment by obelisk79** [comment]
Yes, I think that is the appropriate place for this. Also, it is worth noting that right now there is a PR open in the main repo to set Fusion as the default QtStyle for all of FreeCAD, so this may become less of an issue. Either way, I'm going to close this issue for now. Feel free to comment here or ask me directly on discord if you have any more questions about this.
