### ISSUE TITLE
Weird colors

### ISSUE THREAD

**Issue by leoheck** [obelisk79/OpenTheme#89]
Right-clicking on the tab.

![image](https://github.com/obelisk79/OpenTheme/assets/1277920/6f4fb9b8-4b73-4587-b918-b1ee5c808fb8)

I was thinking here, you have some scss that are loaded to reset or normalize things. 
We could have a setting that sets the whole primaryText and bg to the white the bg to dark on dark theme. 
So cases like this won't easily happen.

Then we won't neet to redefine the colors on every widget.. only special widgets would have primary color redefined when it is needed.

**Comment by obelisk79** [comment]
That green is intentionally there, because when creating the spreadsheet I couldn't find what that color definition was modifying.
