### ISSUE TITLE
Tree view header is not readable

### ISSUE THREAD

**Issue by hasecilu** [obelisk79/OpenTheme#98]
When you activate the **description** and **internal name** columns in the tree view the text is not visible. Light theme is OK.

### Dark FreeCAD
![Screenshot_2024-07-07_16-11-12](https://github.com/obelisk79/OpenTheme/assets/53124818/11d6c098-093d-41ae-a5ed-bba674b249af)

### OpenTheme Dark
![image](https://github.com/obelisk79/OpenTheme/assets/53124818/a43342e8-754a-4275-a58d-d18e85cc7be2)

Edit: Also _Part\_CheckGeometry_ task's headers area affected.
![image](https://github.com/user-attachments/assets/0086c818-af39-4aa6-aa7c-0d8e478be0a8)

**Comment by obelisk79** [comment]
I have resolved this now. You should see an significant improvement after updating your theme through addon-manager.

**Comment by hasecilu** [comment]
Hello, I have tested again and these are the results:

### with overlay off

![image](https://github.com/user-attachments/assets/a82b5c0a-a90a-47f4-b869-87f0db80df2e)

### with overlay on

![image](https://github.com/user-attachments/assets/549fee9e-2610-46a7-a3c9-4de800d61842)

> Edit: Also _Part_CheckGeometry_ task's headers area affected.

This is still the same
